name: Transform apteka
on:
  workflow_dispatch:
  push:
    paths:
      - 'xslt/**.xml'
jobs:
  my_job:
    name: transform
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Transform
        run: xsltproc xslt/style.xsl xslt/LEKZR_2024_19_132733.xml > result/result_17_10_2024.html
      - name: Commit result
        run: |
          git add .
          git commit -am "Push result"
          git push
