name: Transform apteka
on:
  workflow_dispatch:
  push:
    paths:
      - 'xslt/**.xml'
jobs:
  my_job:
    name: transform
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Get date
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD HH_mm_ss_SSS"
      - name: Fetch action
        run: echo "paths=$(echo "ls -R /xslt/")" >> $GITHUB_OUTPUT
        id: get_files

      - name: Output results
        run: |
          echo "Found ${{ steps.get_files.outputs.* }} file(s) with this extension:"
          for i in ${{ steps.get_files.outputs.paths }}; do
          echo $i
          done
      - name: Transform
        run: xsltproc xslt/style.xsl xslt/LEKZR_2024_19_132733.xml > result/result_${{ steps.t1.outputs.day }}_${{ steps.t1.outputs.month }}_${{ steps.t1.outputs.year }}_${{ steps.t1.outputs.hours }}_${{ steps.t1.outputs.minutes }}_${{ steps.t1.outputs.seconds }}.html
      - name: Commit result
        run: |
          git add .
          git commit -am "Push result"
          git push
